services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_api
    restart: always
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      FLASK_APP: src/main.py
      DB_HOST: db
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_PORT: 5432
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --port=5000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      VITE_API_URL: "http://api:5000"
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev

volumes:
  postgres_data: